[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-scripts/a.vim'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'cocopon/vaffle.vim'

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'racer-rust/vim-racer'

[[plugins]]
repo = 'felixhummel/setcolors.vim'

[[plugins]]
repo = 'vim-scripts/VimIM'

#
# ColorSchemas
#

[[plugins]]
repo = 'flazz/vim-colorschemes'

#[[plugins]] # カラースキーマ
#repo = 'tomasr/molokai'

#[[plugins]] # カラースキーマ
#repo = 'w0ng/vim-hybrid'

#hook_add = '''
#set background=dark
#" colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
#" 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
#au MyAutoCmd VimEnter * nested colorscheme elflord
#'''

[[plugins]]
repo = 'tpope/vim-fugitive'

