[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-scripts/a.vim'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'cocopon/vaffle.vim'
hook_add = '''
let g:vaffle_auto_cd = 1
'''

[[plugins]]
repo = 'vim-scripts/VimIM'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
set background=dark
" colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
"   " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
au MyAutoCmd VimEnter * nested colorscheme molokai
'''

[[plugins]]
repo = 'preservim/nerdtree'
hook_add='''
let g:NERDTreeChDirMode=2
let g:NERDTreeShowBookmarks=1
let g:NERDTreeHijackNetrw = 0
let g:NERDTreeMapActivateNode="l"
let g:NERDTreeMapCloseDir="h"
let g:NERDTreeMapToggleHidden="."
'''

[[plugins]]
repo = 'vim-scripts/tComment'
hook_add = '''
let g:tcommentMapLeader1 = '<C-/>'
'''

[[plugins]]
repo = 'vim-scripts/a.vim'

[[plugins]]
repo = 'dag/vim-fish'

