#
# Required:
#
[[plugins]]
repo = 'Shougo/dein.vim'

#
# Minimum
#
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-commentary'
hook_add='''
nmap <C-_> :Commentary<CR>
vmap <C-_> :Commentary<CR>
'''

