#
# Required:
#
[[plugins]]
repo = 'Shougo/dein.vim'

#
# Minimum
#
[[plugins]]
repo = 'cespare/vim-toml'
[[plugins]]
repo = "Shougo/context_filetype.vim"
[[plugins]]
repo = "osyo-manga/vim-precious"

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-commentary'
hook_add='''
nmap <C-_> :Commentary<CR>
vmap <C-_> :Commentary<CR>
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Chiel92/vim-autoformat'
hook_add='''
nmap <S-f> :Autoformat<CR>
vmap <S-f> :Autoformat<CR>
let g:formatters_python = ['autopep8']
'''

[[plugins]]
repo = 'preservim/nerdtree'
hook_add='''
nmap <Space><Space> :NERDTreeVCS<CR>
'''

# [[plugins]]
# repo = "christoomey/vim-tmux-navigator"

