#
# Required:
#
[[plugins]]
repo = 'Shougo/dein.vim'

#
# ColorScheme
#
[[plugins]]
repo = 'tyrannicaltoucan/vim-deep-space'
hook_add = '''
set background=dark
let g:color_scheme = 'deep-space'
'''

#
# Minimum
#
[[plugins]]
repo = 'cespare/vim-toml'
[[plugins]]
repo = "Shougo/context_filetype.vim"
[[plugins]]
repo = "osyo-manga/vim-precious"

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-commentary'
hook_add='''
nmap <C-_> :Commentary<CR>
vmap <C-_> :Commentary<CR>
nmap <C-/> :Commentary<CR>
vmap <C-/> :Commentary<CR>
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Chiel92/vim-autoformat'
hook_add='''
nmap ff :Autoformat<CR>
vmap <S-f> :Autoformat<CR>
let g:formatters_python = ['black']
'''

[[plugins]]
repo = 'preservim/nerdtree'
hook_add='''
nmap <Space>e :NERDTreeVCS<CR>
'''

# [[plugins]]
# repo = "christoomey/vim-tmux-navigator"

# [[plugins]]
# repo = 'junegunn/fzf'

[[plugins]]
repo = 'junegunn/fzf.vim'

