export type ItemType = {
  name: string;
  url?: string;
  img?: string;
};

export const ITEMS: ItemType[] = [
  { name: "漢字" },
  { name: "WEB支那漢", url: "https://www.seiwatei.net/chinakan/chinakan.cgi" },

  { name: "graphics" },
  { name: "raylib", url: "https://www.raylib.com/index.html", img: "https://www.raylib.com/common/img/raylib_logo.png", },
  { name: "cheatsheet", url: "https://www.raylib.com/cheatsheet/cheatsheet.html" },
  { name: "examples", url: "https://github.com/raysan5/raylib/tree/master/examples" },
  { name: "opengl", img: "https://www.opengl.org/img/opengl_logo.jpg" },
  { name: "khrplatform", url: "https://registry.khronos.org/EGL/api/KHR/khrplatform.h" },
  { name: "glcorearb.h", url: "https://registry.khronos.org/OpenGL/api/GL/glcorearb.h" },
  { name: "glext.h", url: "https://registry.khronos.org/OpenGL/api/GL/glext.h" },
  { name: "docs.GL", url: "https://docs.gl/" },
  { name: "glslls", url: "https://github.com/svenstaro/glsl-language-server" },
  { name: "LearnOpenGL", url: "https://learnopengl.com/" },
  { name: "GLFW", url: "https://www.glfw.org/docs/latest/" },
  { name: "WebGL", url: "https://github.com/KhronosGroup/WebGL/tree/main/specs/latest" },
  { name: "DirectXMath", url: "https://learn.microsoft.com/en-us/windows/win32/dxmath/ovw-xnamath-reference-functions-vector3" },
  { name: "imgui-1.87", url: "https://github.com/ocornut/imgui" },
  { name: "ktx", url: "https://www.khronos.org/ktx/" },
  { name: "KTXDeveloperGuide", url: "https://github.com/KhronosGroup/3D-Formats-Guidelines/blob/main/KTXDeveloperGuide.md" },
  { name: "glTF-2.0", url: "https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html" },
  { name: "schema", url: "https://github.com/KhronosGroup/glTF/tree/main/specification/2.0/schema" },
  { name: "glTF(github)", url: "https://github.com/KhronosGroup/glTF" },
  { name: "vulkan-sdk-1.3.264.1", url: "https://www.lunarg.com/vulkan-sdk/" },
  { name: "usd", url: "https://openusd.org/release/index.html", img: "https://openusd.org/dev/api/USDLogoLrgWithAlpha.png" },
  { name: "API", url: "https://openusd.org/release/api/index.html" },
  { name: "Sdf", url: "https://openusd.org/release/api/sdf_page_front.html" },
  { name: "ultraleap", url: "https://docs.ultraleap.com/" },
  { name: "openxr-explorer", url: "https://github.com/maluoi/openxr-explorer" },
  { name: "openxr", img: "https://github.com/KhronosGroup/OpenXR-Docs/raw/main/specification/sources/images/ext_hand_tracking_joint_convention.png" },
  //     <div>
  //       <img
  //         height="64"
  //         src="https://download.blender.org/branding/community/blender_community_badge_white.png"
  //       />
  //       { name: "Blender-3.5", url: "https://www.blender.org/" },
  //       <a href="https://www.youtube.com/watch?v=tVc8PtAH9Rg&ab_channel=Blender"
  //         >20230228 #219</a
  //       >
  //       <a href="https://www.youtube.com/watch?v=tnTq49GUguQ&ab_channel=Blender"
  //         >20220802 #201</a
  //       >
  //     </div>

  { name: "A-FRAME" },
  { name: "UECS", url: "https://github.com/jprochazk/uecs" },
  { name: "A-FRAME", url: "https://aframe.io/docs/1.4.0/introduction/" },
  { name: "webxr-samples", url: "https://immersive-web.github.io/webxr-samples/" },
  { name: "webxr-handtracking", url: "https://webxr-handtracking.vercel.app/" },
  { name: "hand", url: "./aframe_hand.html" },
  { name: "custom", url: "./custom_hand.html" },
  { name: "physics-extras", url: "https://github.com/wmurphyrd/aframe-physics-extras" },
  { name: "a-blast", url: "https://github.com/aframevr/a-blast/" },
  { name: "GitHub - gftruj/aframe-hand-tracking-controls-extras", url: "https://github.com/gftruj/aframe-hand-tracking-controls-extras" },
  { name: "GitHub - marlon360/webxr-handtracking", url: "https://github.com/marlon360/webxr-handtracking" },
  { name: "GitHub - c-frame/aframe-super-hands-component", url: "https://github.com/c-frame/aframe-super-hands-component" },
  { name: "GitHub - t100ta/tfjs-aframe-handtracking", url: "https://github.com/t100ta/tfjs-aframe-handtracking" },
  { name: "GitHub - AdaRoseCannon/handy-work", url: "https://github.com/AdaRoseCannon/handy-work" },

  { name: "lang" },
  { name: "fsharp", url: "https://learn.microsoft.com/ja-jp/dotnet/fsharp/" },
  { name: "go", img: "/gopher.png", url: "https://go.dev/" },
  { name: "StandardLibrary", url: "https://pkg.go.dev/std" },
  { name: "bubbletea", url: "https://github.com/charmbracelet/bubbletea" },
  { name: "lua", img: "https://www.lua.org/images/logo.gif", url: "http://www.lua.org/" },
  { name: "reference 5.4", url: "https://www.lua.org/manual/5.4/" },
  { name: "reference 5.1", url: "https://www.lua.org/manual/5.1/" },
  { name: "C Libraries", url: "https://www.lua.org/pil/26.2.html" },
  { name: "ffi", url: "https://luajit.org/ext_ffi_tutorial.html" },
  { name: "busted", url: "https://lunarmodules.github.io/busted/" },
  { name: "Penlight", url: "https://lunarmodules.github.io/Penlight/index.html" },
  { name: "LuaLanguageServer", url: "https://luals.github.io/wiki/" },
  { name: "modules", url: "https://github.com/LuaLS/lua-language-server/tree/master/3rd" },
  { name: "luv", url: "https://github.com/luvit/luv/blob/master/docs.md" },
  { name: "LÖVE", url: "https://love2d.org/wiki/Main_Page" },
  { name: "EmmyLuaAnnotation", url: "https://emmylua.github.io/annotation.html" },
  { name: "naygos", url: "https://github.com/nyaosorg/nyagos/blob/master/docs/01-Install_ja.md", img: "https://raw.githubusercontent.com/nyaosorg/nyagos/master/Etc/nyagos.png" },
  { name: "LuaJit", url: "https://github.com/LuaJIT/LuaJIT" },
  { name: "luarocks", url: "https://luarocks.org/" },
  { name: "c++", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/180px-ISO_C%2B%2B_Logo.svg.png" },
  { name: "meson", url: "https://mesonbuild.com/" },
  { name: "asio", url: "https://think-async.com/Asio/asio-1.24.0/doc/asio/reference.html" },
  { name: "nlohmann json", url: "https://json.nlohmann.me/" },
  { name: "llvm-16.0.6", url: "https://llvm.org/" },
  { name: "clang-format", url: "https://clang.llvm.org/docs/ClangFormatStyleOptions.html" },
  { name: "vcpkg", url: "https://github.com/microsoft/vcpkg" },
  { name: ".NET6", url: "https://docs.microsoft.com/ja-jp/dotnet/core/whats-new/dotnet-6" },
  { name: "C#11", url: "https://learn.microsoft.com/ja-jp/dotnet/csharp/whats-new/csharp-version-history" },
  { name: "zig", img: "https://github.com/ziglang/logo/raw/master/zero.svg", url: "https://ziglang.org/" },
  { name: "std", url: "https://ziglang.org/documentation/master/std/#root" },
  { name: "awesome-zig", url: "https://github.com/C-BJ/awesome-zig" },
  { name: "Zig Compiler Internals", url: "https://www.youtube.com/watch?v=8MbREuiLQrM&ab_channel=ZigSHOWTIME" },
  { name: "python", img: "https://www.python.org/static/img/python-logo-large.c36dccadd999.png", url: "https://www.python.org/" },
  { name: "pep", url: "https://peps.python.org/" },
  { name: "prompt-toolkit", url: "https://github.com/prompt-toolkit/python-prompt-toolkit" },
  { name: "doit", url: "https://pydoit.org/" },
  { name: "PEP-567", url: "https://peps.python.org/pep-0567/" },
  { name: "docutils", url: "https://docutils.sourceforge.io/" },
  { name: "xonsh-0.11.0", url: "https://xon.sh/" },
  { name: "sphinx-4.5", url: "https://www.sphinx-doc.org/en/master/" },
  { name: "nikola", url: "https://getnikola.com/" },
  { name: "PyGLM", url: "https://github.com/Zuzu-Typ/PyGLM/wiki" },

  { name: "term" },
  { name: "wezterm", url: "https://wezfurlong.org/wezterm/index.html" },
  { name: "aqua", url: "https://aquaproj.github.io/" },
  { name: "emoji", url: "https://unicode.org/emoji/charts/full-emoji-list.html" },
  { name: "neovim", img: "https://raw.githubusercontent.com/neovim/neovim.github.io/master/logos/neovim-logo-300x87.png", url: "https://neovim.io" },
  { name: "neovim help", url: "https://neovim.io/doc/user/" },
  { name: "nvim lsp", url: "https://neovim.io/doc/user/lsp.html" },
  { name: "pluginlist", url: "https://yutkat.github.io/my-neovim-pluginlist/" },
  { name: "lua guide", url: "https://github.com/willelz/nvim-lua-guide-ja/blob/master/README.ja.md" },
  { name: "server_configurations", url: "https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md" },
  { name: "nullls", url: "https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md" },
  { name: "vim-9.0", url: "https://www.vim.org/" },
  { name: "lsp", url: "https://microsoft.github.io/language-server-protocol/" },
  { name: "NerdFonts", url: "https://www.nerdfonts.com/" },
  { name: "msys2", url: "https://www.msys2.org/" },
  { name: "awesome-bash", url: "https://github.com/awesome-lists/awesome-bash" },
  { name: "tmux", url: "https://github.com/tmux/tmux" },
  { name: "powerline-shell", url: "https://github.com/b-ryan/powerline-shell" },
  { name: "zellij", url: "https://github.com/zellij-org/zellij" },
  { name: "FTXUI-4.0", url: "https://arthursonzogni.github.io/FTXUI/" },

  { name: "gtk" },
  { name: "gtkmm", url: "https://developer-old.gnome.org/gtkmm-tutorial/stable/" },
  { name: "GNOME sources", url: "https://download.gnome.org/sources/" },
  { name: "GNOME glab", url: "https://gitlab.gnome.org/GNOME" },
  { name: "GTK-4.8", url: "https://www.gtk.org/" },
  { name: "GTK Development Blog", url: "https://blog.gtk.org/" },
  { name: "polybar", url: "https://github.com/polybar/polybar/wiki/" },
  { name: "gst", url: "https://gstreamer.freedesktop.org/src/" },

  { name: "web", img: "https://www.w3.org/html/logo/downloads/HTML5_Badge_64.png" },
  { name: "HTML Living Standard", url: "https://html.spec.whatwg.org/multipage/parsing.html" },
  { name: "react", url: "https://ja.react.dev/" },
  { name: "ReactFlow", url: "https://reactflow.dev/" },
  { name: "mermaid", url: "https://mermaid.js.org/" },
  { name: "mozilla", url: "https://developer.mozilla.org/ja/docs/Web" },
  { name: "The_head_metadata_in_HTML", url: "https://developer.mozilla.org/ja/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML" },
  { name: "flexbox", url: "https://developer.mozilla.org/ja/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox" },
  { name: "gatsby", url: "https://www.gatsbyjs.com/docs/" },
  { name: "TypedArray", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray" },

  { name: "WebRTC" },
  { name: "janus", url: "https://github.com/meetecho/janus-gateway" },
  { name: "mediasoup", url: "https://mediasoup.org/documentation/" },
  { name: "WebRTC Test Landing Page", url: "https://mozilla.github.io/webrtc-landing/" },

  { name: "Linux", img: "https://isc.tamu.edu/~lewing/linux/sit3-shine.7.gif" },
  { name: "Linux", url: "https://www.kernel.org/" },
  { name: "Ubuntu", url: "https://gihyo.jp/list/group/Ubuntu-Weekly-Recipe" },
  { name: "GentooHandbook", url: "https://wiki.gentoo.org/wiki/Handbook:AMD64" },
  { name: "portage", url: "https://wiki.gentoo.org/wiki/Useful_Portage_tools" },
  { name: "LFS-11.3", url: "https://www.linuxfromscratch.org/lfs/view/stable/" },
  { name: "ArchLinux", url: "https://www.archlinux.jp/" },
  { name: "Docker", url: "https://matsuand.github.io/docs.docker.jp.onthefly/" },
  { name: "multi stage build", url: "https://matsuand.github.io/docs.docker.jp.onthefly/develop/develop-images/multistage-build/" },
];
