#!/bin/sh
#
# These things are run when an Openbox X Session is started.
# You may place a similar script in $HOME/.config/openbox/autostart
# to run user-specific things.
#

# If you want to use GNOME config tools...
#
#if test -x /usr/lib/openbox/gnome-settings-daemon >/dev/null; then
#  /usr/lib/openbox/gnome-settings-daemon &
#elif which gnome-settings-daemon >/dev/null 2>&1; then
#  gnome-settings-daemon &
#fi

# If you want to use XFCE config tools...
#
#xfce-mcs-manager &
if which picom > /dev/null 2>&1; then
    picom -b
fi

if which polybar > /dev/null 2>&1; then
    ~/.config/polybar/launch.sh
elif which tint2 > /dev/null 2>&1; then
    tint2&
fi

if which conky > /dev/null 2>&1; then
    conky&
fi

if which copyq > /dev/null 2>&1; then
    copyq&
fi

if which volumeicon > /dev/null 2>&1; then
    volumeicon&
fi

if which pluseaudio > /dev/null 2>&1; then
    pluseaudio --start
fi

